[package]
name = "cr8s"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
diesel_cli ="2.1.0"
diesel = {version= "2.1.0", features=["postgres","chrono"]}
chrono="0.4"
